#ifndef ERRORS_H
#define ERRORS_H

#define HEAP_MEMORY_NOT_ALIGNED -301
#define HEAP_TABLE_LOW_BYTES_AVAILABLE -302
#define HEAP_AVAILABLE_MEMORY_LESS_THAN_BLOCK -303
#define HEAP_MEMORY_NOT_MEMORY_LEFT -304

#define PAGING_MEMORY_NOT_ALIGNED -401

#define SYSTEM_FAIL -49
#define INVALID_ARGUMENT -50
#define NOT_IMPLEMENTED -255
#define WRONG_FILESYSTEM -200

#define DISK_INVALID_DISK -101
#define DISK_FAIL_TO_READ_STREAM -201
#define DISK_FAIL_SET_STREAM_POS -202

#define FS_PATH_INVALID -501
#define FS_CANNOT_GET_FILE -502

#endif
