#ifndef ERRORS_H
#define ERRORS_H

#define HEAP_MEMORY_NOT_ALIGNED -1
#define HEAP_TABLE_LOW_BYTES_AVAILABLE -2
#define HEAP_AVAILABLE_MEMORY_LESS_THAN_BLOCK -3

#define PAGING_MEMORY_NOT_ALIGNED -1

#define INVALID_ARGUMENT -50

#define DISK_INVALID_DISK -1

#define FS_PATH_INVALID -1

#endif
